### ISSUE TITLE
Meteor OAuth 2.0 (0.6.4) does not work with current Instagram handshake

### ISSUE THREAD

**Issue by jackchi** [adams-zz/Instahood#3]
Exception while bundling application:
Error: ENOENT, no such file or directory '/Users/guest/.meteor/packages/accounts-oauth2-helper/package.js'
    at Object.fs.openSync (fs.js:338:18)
    at Object.fs.openSync (/Users/guest/.meteor/tools/cc18dfef9e/lib/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:68:26)
    at Object.fs.readFileSync (fs.js:182:15)
    at _.extend.initFromPackageDir (/Users/guest/.meteor/tools/cc18dfef9e/tools/packages.js:163:19)
    at _.extend.initFromWarehouse (/Users/guest/.meteor/tools/cc18dfef9e/tools/packages.js:197:10)
    at Object._.extend.get (/Users/guest/.meteor/tools/cc18dfef9e/tools/packages.js:353:15)
    at self.api.use (/Users/guest/.meteor/tools/cc18dfef9e/tools/bundler.js:111:28)
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/guest/.meteor/tools/cc18dfef9e/lib/node_modules/underscore/underscore.js:78:11)
    at Object.self.api.use (/Users/guest/.meteor/tools/cc18dfef9e/tools/bundler.js:110:9)
    at null.on_use_handler (/Users/guest/Desktop/hack-meat/Instahood/packages/accounts-instagram/package.js:7:9)
    at _.extend.use (/Users/guest/.meteor/tools/cc18dfef9e/tools/bundler.js:464:11)
    at self.api.use (/Users/guest/.meteor/tools/cc18dfef9e/tools/bundler.js:114:21)
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/guest/.meteor/tools/cc18dfef9e/lib/node_modules/underscore/underscore.js:78:11)
    at Object.self.api.use (/Users/guest/.meteor/tools/cc18dfef9e/tools/bundler.js:110:9)
    at _.extend.init_from_app_dir [as on_use_handler](/Users/guest/.meteor/tools/cc18dfef9e/tools/packages.js:238:11)
    at _.extend.use (/Users/guest/.meteor/tools/cc18dfef9e/tools/bundler.js:464:11)
    at Object.exports.bundle (/Users/guest/.meteor/tools/cc18dfef9e/tools/bundler.js:873:12)
    at /Users/guest/.meteor/tools/cc18dfef9e/tools/run.js:697:26
    at exports.inFiber (/Users/guest/.meteor/tools/cc18dfef9e/tools/fiber-helpers.js:24:12)

**Comment by nicolsondsouza** [comment]
It's working for me.
check my app instagrampackage.meteor.com
